name: Testing

on:
  push:
  pull_request:

jobs:
  modern:
    name: Node v${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16
          - 14
          - 12
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --production
      - name: Run unit tests
        run: yarn test
        env:
          FORCE_COLOR: 2
  legacy:
    name: Node v${{ matrix.node-version }} (Legacy)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10
          - 8
          - 6
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile --production
      - name: Run unit tests
        run: yarn test
        env:
          FORCE_COLOR: 2